update neutron tests
so that they will not conflict between multiple
neutron controllers.

the current tests create the same named network which
can lead to conflicts between nodes that cause validation
failures.

this patch makes the created networks unique per node.

diff --git a/templates/tests/neutron.sh.erb b/templates/tests/neutron.sh.erb
--- a/templates/tests/neutron.sh.erb
+++ b/templates/tests/neutron.sh.erb
@@ -5,18 +5,20 @@ function fail {
   exit 2
 }
 
+
 if [ -f /root/openrc ]; then
   source /root/openrc
+  netname=testnet<%= @net_number %>
   neutron net-list -D || fail 'neutron net-list failed'
-  neutron net-create testnet || fail 'neutron net-create failed'
-  netid=`neutron net-list -D | awk '/[a-z][a-z]*[0-9][0-9]*/ {print $2}' | head -1`
+  neutron net-create $netname || fail 'neutron net-create failed'
+  netid=`neutron net-list -D | grep $netname |  awk '/[a-z][a-z]*[0-9][0-9]*/ {print $2}' | head -1`
   neutron subnet-create $netid 10.0.0.0/24 || fail 'neutron subnet-create failed'
   neutron port-create $netid || fail 'neutron port-create failed'
   for port in `neutron port-list | awk '/[a-z][a-z]*[0-9][0-9]*/ {print $2}'`; do
-    neutron port-delete $port || fail 'neutron port-delete failed'
+    neutron port-delete $port || true
   done
   for net in `neutron net-list -D  | awk '/[a-z][a-z]*[0-9][0-9]*/ {print $2}'`; do
-    neutron net-delete $net || fail 'neutron net-delete failed'
+    neutron net-delete $net || true
   done
 else
   echo 'Critical: Openrc does not exist'
